import "./globals.css";

export const metadata = {
  title: "SGCU Borrow System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-gradient-to-b from-[#F3447B] to-[#FEA1BE] pt-5`}
      >
        {children}
      </body>
    </html>
  );
}
