import { Inter } from "next/font/google";
import "./globals.css";

// Define the font
const inter = Inter({
  subsets: ["latin"], // You can add more subsets if needed (e.g., 'latin', 'latin-ext', 'cyrillic', etc.)
});
export const metadata = {
  title: "SGCU Borrow System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen bg-gradient-to-b from-[#F3447B] to-[#FEA1BE] pt-5`}
      >
        {children}
      </body>
    </html>
  );
}
